### ISSUE TITLE
make not working

### ISSUE THREAD

**Issue by shkumesh** [EDS-APHP/pySyntheticDatasetGenerator#2]
Getting below error:

make clean
make[1]: Entering directory '/home/ams/pySyntheticDatasetGenerator'
rm -rf output/* &&\
find tmp/ -name "*.csv"  -delete
make[1]: Leaving directory '/home/ams/pySyntheticDatasetGenerator'
make run
make[1]: Entering directory '/home/ams/pySyntheticDatasetGenerator'
python main.py --core=4 --conf=config/example.yaml  --locale fr_FR
  File "main.py", line 46
    jp.available.append(JobFactory.factory({**gen_params,  **params}))
                                             ^
SyntaxError: invalid syntax
Makefile:17: recipe for target 'run' failed
make[1]: *** [run] Error 1
make[1]: Leaving directory '/home/ams/pySyntheticDatasetGenerator'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by parisni** [comment]
what python version / os version are you using

**Comment by shkumesh** [comment]
Sorry, we were able to resolve this. The problem was with the python version.
